name: Update Bedrock Status

on:
  schedule: [{ cron: "*/5 * * * *" }]   # alle 5 Minuten
  workflow_dispatch: {}

permissions:
  contents: write

env:
  FILEPATH: "data/status.json"
  KEEP: "2016"                 # ~7 Tage bei 5-Minuten-Intervallen
  API_URL: "https://mc-server-status-black.vercel.app/api/bedrock"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Anti-burst jitter (0–45s)
        shell: bash
        run: |
          sleep $((RANDOM % 46))

      - name: Install jq & curl & Python
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl python3

      # --- status.json sicherstellen ---
      - name: Ensure status file exists
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "$FILEPATH")"
          if [ ! -s "$FILEPATH" ]; then
            jq -n \
              --arg name "Minecraft Bedrock" \
              --arg host "important-instrumentation.gl.at.ply.gg" \
              --argjson port 18232 \
              '{generated:"", service:{name:$name, host:$host, port:$port}, history:[]}' \
              > "$FILEPATH"
            echo "Created $FILEPATH"
          else
            echo "Found $FILEPATH"
          fi

      # --- robuster Fetch: Fehler => offline statt null ---
      - name: Pull latest status from Vercel API (robust)
        id: ping
        shell: bash
        run: |
          set -euo pipefail
          : "${API_URL:?API_URL not set}"
          if ! curl --fail --show-error --silent --max-time 12 "$API_URL" -o resp.json; then
            echo "curl failed → treat as offline"
            echo '{"ok":false,"generated":null,"service":{}}' > resp.json
          fi
          if ! jq -e 'has("ok") and (.ok|type=="boolean")' resp.json >/dev/null; then
            echo "response invalid → force ok=false"
            jq '.ok=false' resp.json > resp.fixed.json && mv resp.fixed.json resp.json
          fi
          echo "ok=$(jq -r '.ok' resp.json)"                         >> "$GITHUB_OUTPUT"
          echo "ts=$(jq -r '.generated // now|todate' resp.json)"    >> "$GITHUB_OUTPUT"
          echo "host=$(jq -r '.service.host // empty' resp.json)"    >> "$GITHUB_OUTPUT"
          echo "port=$(jq -r '.service.port // empty' resp.json)"    >> "$GITHUB_OUTPUT"

      - name: Append + trim history
        shell: bash
        run: |
          set -euo pipefail
          ts='${{ steps.ping.outputs.ts }}'
          ok='${{ steps.ping.outputs.ok }}'
          host='${{ steps.ping.outputs.host }}'
          port='${{ steps.ping.outputs.port }}'
          : "${ts:=$(date -u +%FT%TZ)}"
          : "${ok:=false}"

          jq --arg ts "$ts" \
             --argjson ok ${ok} \
             --arg host "$host" \
             --argjson port ${port:-0} \
             --argjson keep ${KEEP:-2016} '
              if .service == null then .service = {} else . end |
              .service.host = (if $host != "" then $host else .service.host end) |
              .service.port = (if $port != 0  then $port else .service.port end) |
              .history += [{"ts":$ts,"ok":$ok}] |
              .history |= (.[-($keep|tonumber):] // .) |
              .generated = $ts
            ' "$FILEPATH" > "$FILEPATH.tmp"
          mv "$FILEPATH.tmp" "$FILEPATH"
          echo "Updated $FILEPATH"

      # -------- LATENCY: robust & self-contained --------

      - name: Ensure latency.json exists
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p public
          [ -f public/latency.json ] || echo "[]" > public/latency.json

      - name: Write latency script (RakNet UDP ping)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p scripts
          cat > scripts/bedrock_latency.py <<'PY'
import os, socket, struct, time, json, statistics, random
HOST = os.environ.get("HOST", "important-instrumentation.gl.at.ply.gg")
PORT = int(os.environ.get("PORT", "18232"))
SAMPLES = int(os.environ.get("SAMPLES", "5"))
TIMEOUT = float(os.environ.get("TIMEOUT", "1.2"))
RAKNET_MAGIC = bytes.fromhex("00ffff00fefefefefdfdfdfd12345678")

def bedrock_ping_once(host, port, timeout=1.0):
    pkt = bytearray([0x01])  # unconnected ping
    now = int(time.time() * 1000)
    pkt += struct.pack(">Q", now)
    pkt += RAKNET_MAGIC
    pkt += struct.pack(">Q", random.getrandbits(64))
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.settimeout(timeout)
            t0 = time.perf_counter()
            s.sendto(pkt, (host, port))
            data, _ = s.recvfrom(2048)
            rtt_ms = int((time.perf_counter() - t0) * 1000)
            if not data or data[0] != 0x1c:  # unconnected pong
                return None
            if RAKNET_MAGIC not in data:
                return None
            return rtt_ms
    except Exception:
        return None

def main():
    vals = []
    for _ in range(SAMPLES):
        ms = bedrock_ping_once(HOST, PORT, TIMEOUT)
        vals.append(ms)
        time.sleep(0.05)
    filtered = [v for v in vals if v is not None]
    out = {
        "ts": time.strftime("%Y-%m-%dT%H:%M:%S")+"Z",
        "p50_ms": int(statistics.median(filtered)) if filtered else None,
        "p95_ms": int(sorted(filtered)[max(0, int(0.95*(len(filtered)-1)))]) if filtered else None,
        "samples": [ (v if v is not None else None) for v in vals ],
    }
    print(json.dumps(out))

if __name__ == "__main__":
    main()
PY

      - name: Prepare HOST/PORT for latency
        id: latenv
        shell: bash
        run: |
          set -euo pipefail
          host=$(jq -r '.service.host // empty' "$FILEPATH")
          port=$(jq -r '.service.port // empty' "$FILEPATH")
          : "${host:=important-instrumentation.gl.at.ply.gg}"
          : "${port:=18232}"
          echo "host=$host" >> "$GITHUB_OUTPUT"
          echo "port=$port" >> "$GITHUB_OUTPUT"

      - name: Measure Bedrock UDP latency (robust)
        shell: bash
        env:
          HOST: ${{ steps.latenv.outputs.host }}
          PORT: ${{ steps.latenv.outputs.port }}
          SAMPLES: "5"
          TIMEOUT: "1.2"
        run: |
          set -euo pipefail
          mkdir -p public
          # Messung – Fehler abfangen
          set +e
          python3 scripts/bedrock_latency.py > latency_one.json
          rc=$?
          set -e
          if [ $rc -ne 0 ] || ! jq -e . latency_one.json >/dev/null 2>&1; then
            echo "Latency measure failed → write fallback with nulls"
            printf '{"ts":"%s","p50_ms":null,"p95_ms":null,"samples":[null,null,null,null,null]}\n' "$(date -u +%FT%TZ)" > latency_one.json
          fi
          # Ziel initialisieren & anhängen
          [ -f public/latency.json ] || echo "[]" > public/latency.json
          tmp=$(mktemp)
          jq -s '.[0] + [.[1]]' public/latency.json latency_one.json > "$tmp" && mv "$tmp" public/latency.json
          echo "latency appended"

      - name: Trim latency.json (90 days)
        shell: bash
        run: |
          set -euo pipefail
          now=$(date -u +%s)
          tmp=$(mktemp)
          jq --arg now "$now" '
            map(select(
              (try (.ts | sub("Z$";"") | fromdateiso8601) catch 0) >= ($now|tonumber - 90*24*3600)
            ))
          ' public/latency.json > "$tmp" && mv "$tmp" public/latency.json

      # --------------- Commit ----------------
      - name: Commit & push (data + latency)
        shell: bash
        run: |
          set -euo pipefail
          if git diff --quiet -- "$FILEPATH" "public/latency.json"; then
            echo "No changes"
          else
            git config user.name  "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add "$FILEPATH" "public/latency.json"
            git commit -m "history+latency: $(date -u +%FT%TZ) [skip vercel]"
            git push origin main
            echo "Pushed update"
          fi
