name: Store Bedrock History
on:
  schedule: [{ cron: "*/5 * * * *" }]
  workflow_dispatch: {}
permissions: { contents: write }
env:
  FILEPATH: "data/status.json"
  KEEP: "2016"  # 7 Tage
  API_URL: "https://mc-server-status-black.vercel.app/api/bedrock"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { ref: main, persist-credentials: true }
      - run: sudo apt-get update && sudo apt-get install -y jq curl
      - name: ensure file
        run: |
          mkdir -p "$(dirname "$FILEPATH")"
          [ -s "$FILEPATH" ] || echo '{"generated":"","service":{"name":"Minecraft Bedrock","host":"important-instrumentation.gl.at.ply.gg","port":18232},"history":[]}' > "$FILEPATH"
      - name: pull from vercel api
        id: ping
        run: |
          set -e
          curl -fsSL "$API_URL" -o resp.json
          echo "ok=$(jq -r '.ok // \"null\"' resp.json)" >> $GITHUB_OUTPUT
          echo "ts=$(jq -r '.generated' resp.json)" >> $GITHUB_OUTPUT
          echo "host=$(jq -r '.service.host' resp.json)" >> $GITHUB_OUTPUT
          echo "port=$(jq -r '.service.port' resp.json)" >> $GITHUB_OUTPUT
      - name: append + trim
        run: |
          ts='${{ steps.ping.outputs.ts }}'
          ok='${{ steps.ping.outputs.ok }}'
          host='${{ steps.ping.outputs.host }}'
          port='${{ steps.ping.outputs.port }}'
          jq --arg ts "$ts" --argjson ok ${ok:-null} --arg host "$host" --argjson port $port --argjson keep $KEEP '
            .service.host=$host | .service.port=$port |
            .history += [{"ts":$ts,"ok":$ok}] |
            .history |= (.[-($keep|tonumber):] // .) |
            .generated=$ts
          ' "$FILEPATH" > "$FILEPATH.tmp" && mv "$FILEPATH.tmp" "$FILEPATH"
      - name: commit (skip vercel)
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          if ! git diff --quiet -- "$FILEPATH"; then
            git add "$FILEPATH"
            git commit -m "history: $(date -u +"%Y-%m-%dT%H:%M:%SZ") [skip vercel]"
            git push origin main
          else
            echo "no changes"
          fi
